services:
  - type: web
    name: resume-extractor-backend
    runtime: python
    plan: free
    buildCommand: pip install -r "resume extractor/backend/requirements.txt"
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000 --app-dir "resume extractor/backend"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: GEMINI_API_KEY
        sync: false
